name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Deploy to AWS
        env:
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > deploy_key
          chmod 600 deploy_key
          ssh -i deploy_key $AWS_USERNAME@$AWS_HOST << 'EOF'
            cd app/backend
            git pull origin main
            npm install
            npm run build
            npm run start:pm2
          EOF
        shell: bash

      - name: Clean up deploy key
        run: rm deploy_key
        if: always()
